### PR TITLE
Birthday Paradox: issue 24

### PR DESCRIPTION
**Pull request by shaunak56**
I have added the birthday paradox code in cpp with a basic explanation and comments. kindly merge the same :)

### CODE REVIEW

**Comment by shaunak56** [comment]
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

It shows this message on hacktoberfest website for this PR. Kindly add the required topic in your repository, Thank you

**Comment by Subhas-08** [comment]
@shaunak56  yeah I have add the hacktoberfest  level in my repo , plz check it

**Comment by shaunak56** [comment]
You have to add "hacktoberfest" and not "hacktoberfest2020" to the best of my knowledge. Thank you

**Comment by Prodip-Kumar-Paul** [comment]
@shaunak56  yeah plz check it again, btw thanks for this info

**Comment by Subhas-08** [comment]
@shaunak56 yeah I add this also plz it again, btw thanks for this info

**Comment by shaunak56** [comment]
done! thank you

**Pull request merged**
