### PR TITLE
Added KMP algorithm

### PR DESCRIPTION
**Pull request by Harshit564**
Issue #21

### CODE REVIEW

**Comment by Harshit564** [comment]
Your PR is showing ineligible in hacktoberfest site. @Subhas-08 
```
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.
```

**Comment by Harshit564** [comment]
@Subhas-08 have you checked this issue??

**Comment by Subhas-08** [comment]
@Harshit564  yeah I have solve that issue plz check it again  and thanks for telling about that issue

**Comment by Harshit564** [comment]
Welcome, @Subhas-08 bro!
How did u solve that issue? 
I also have the same issue with my repo. Can u help me?

**Comment by Subhas-08** [comment]
@Harshit564 yeah sure , go to repo and level "hacktoberfsest"

**Pull request merged**
